var CommentConstants = {
  POST_ADD: 'POST_ADD',
  POST_DELETE: 'POST_DELETE',
  POST_EDIT: 'POST_EDIT',
  POST_FETCHPAGE: 'POST_FETCHPAGE',
  POST_FETCHUSERPAGE: 'POST_FETCHUSERPAGE',
  POST_UPVOTE: 'POST_UPVOTE',
  POST_DOWNVOTE: 'POST_DOWNVOTE',
  POST_UPDATE: 'POST_UPDATE',
  POST_DELETE: 'POST_DELETE'
};

module.exports = CommentConstants;