var FriendConstants = {
	ADD_FRIEND: "ADD_FRIEND",
	REMOVE_FRIEND: "REMOVE_FRIEND",
  FETCH_FRIEND: "",
  SET_FRIENDSTATUS: "SET_FRIENDSTATUS",
  FETCH_FRIENDLIST: "FETCH_FRIENDLIST",
};

module.exports = FriendConstants;