var ThreadConstants = {
  ADD: 'ADD',
  SEARCH: 'SEARCH',
  FETCHTHREAD: 'FETCHTHREAD',
  FETCHPAGE: 'FETCHPAGE',
  FETCHUSERPAGE: 'FETCHUSERPAGE',
  FETCHOTHERPAGE: 'FETCHOTHERPAGE',
  UPVOTE: 'UPVOTE',
  DOWNVOTE: 'DOWNVOTE',
  UPDATE: 'UPDATE',
  DELETE: 'DELETE'
};

module.exports = ThreadConstants;